# Generated by Django 4.1.1 on 2022-10-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtora', models.CharField(max_length=200, unique=True)),
                ('nome_contato', models.CharField(blank=True, max_length=200, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, unique=True)),
                ('video', models.CharField(blank=True, max_length=500, unique=True)),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='media/publicidade/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('video', models.CharField(blank=True, max_length=500, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='media/youtube/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('video', models.CharField(blank=True, max_length=500, unique=True)),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='media/teatro/%y/%m/%d')),
                ('personagem', models.CharField(max_length=200, unique=True)),
                ('director', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nome', to='api_portfolio.director')),
                ('produtora', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produtora', to='api_portfolio.produtora')),
            ],
        ),
        migrations.CreateModel(
            name='Locucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('video', models.CharField(blank=True, max_length=500, unique=True)),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='media/locucao/%y/%m/%d')),
                ('director', models.ManyToManyField(blank=True, to='api_portfolio.director')),
                ('produtora', models.ManyToManyField(blank=True, to='api_portfolio.produtora')),
            ],
        ),
        migrations.CreateModel(
            name='AudioVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('video', models.CharField(blank=True, max_length=500, unique=True)),
                ('data', models.DateField(blank=True)),
                ('ativo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='media/audiovisual/%y/%m/%d')),
                ('director', models.ManyToManyField(to='api_portfolio.director')),
                ('produtora', models.ManyToManyField(blank=True, to='api_portfolio.produtora')),
            ],
        ),
    ]
