# Generated by Django 4.1.1 on 2022-10-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0002_album_alter_audiovisual_image_teatro_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='teatro',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='audioVisual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_portfolio.audiovisual'),
        ),
        migrations.AddField(
            model_name='album',
            name='teatro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_portfolio.teatro'),
        ),
        migrations.AddField(
            model_name='album',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_portfolio.book'),
        ),
    ]
