# Generated by Django 4.1.1 on 2022-10-17 21:15

import api_portfolio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0003_book_remove_teatro_album_album_audiovisual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='audioVisual',
        ),
        migrations.RemoveField(
            model_name='album',
            name='teatro',
        ),
        migrations.CreateModel(
            name='Trabalhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(choices=[('Teatro', 'Teatro'), ('Audio Visual', 'Audio Visual'), ('Locucao', 'Locucao'), ('Youtube', 'Youtube'), ('Publicidade', 'Publicidade')], default=api_portfolio.models.Youtube, max_length=12)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('video', models.CharField(blank=True, max_length=500, unique=True)),
                ('data', models.DateField(blank=True)),
                ('ativo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/audiovisual/%y/%m/%d')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_portfolio.director')),
                ('produtora', models.ManyToManyField(blank=True, to='api_portfolio.produtora')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='trabalhos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_portfolio.trabalhos'),
        ),
    ]
