# Generated by Django 4.1.1 on 2022-10-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0004_remove_album_audiovisual_remove_album_teatro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos',
            name='personagem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
